apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgbouncer.fullname" . }}-auth
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
type: Opaque
stringData:
  userlist.txt: |
    {{- range .Values.users }}
    "{{ .name }}" "{{ .password }}"
    {{- end }} 