apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgbouncer.fullname" . }}
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None  # Headless service için
  ports:
    - port: {{ .Values.service.port }}
      targetPort: pgbouncer
      protocol: TCP
      name: pgbouncer
  selector:
    {{- include "pgbouncer.selectorLabels" . | nindent 4 }}
